---
applications:
- name: APPNAME
  memory: 1G
  buildpacks: 
    - java_buildpack_offline
  env:
    DT_NODE_ID: APPNAME
    DT_CUSTOM_PROP: DEPLOYMENT_GRP_NAME=SPRING-MUSIC-DTGRP DEPLOYMENT_COLOR=SPRING-MUSIC-APPCOLOR
    DEPLOYMENT_GRP_NAME: SPRING-MUSIC-DTGRP
    DELAY: 10000
    incrementthistoforcenewrelease: 1
